-- =============================================================================
-- Vepari: OWNER / PARTNER accounts and CLIENT / CUSTOMER records
-- Project: vepari (zzghblixuxhjxpxzugac). Run blocks in Supabase → SQL Editor.
-- Runbook: docs/operations/onboarding.md
-- =============================================================================
--
-- How Vepari stores this (existing schema, nothing invented):
--
--   auth.users              the LOGIN: email <username>@login.vepari.invalid + password
--   auth.identities         the login's email identity (needed to sign in)
--   public.app_users        username + display name for that login (same id as auth.users)
--   public.tenants          ONE business. Ours = the manufacturing organization
--                           (slug 'vepari-manufacturer')
--   public.business_profiles  the business name, phone and address shown on bills
--   public.tenant_members   links a login to the business with role 'owner' or 'staff'
--   public.customers        the business's CLIENTS: jewellers who order from us.
--                           A client has NO login; it is a record inside our business.
--
--   One login belongs to exactly one business. All 5 partners are role 'owner' of
--   the SAME business. Owners add staff in the app (More → Staff), not here.
--
-- Records created on 2026-10-02 (the ids are the real ones from the database):
--
--   Business  vepari-manufacturer  "Vepari Manufacturer (Demo)"
--             tenant_id 1084275c-161a-423c-acd9-bbc718668a56
--   Owners    krish         5f237907-6bdf-4899-92a9-9f83edc8c2d6   (created the business)
--             sujal         b300015b-ddf2-4e58-9ed3-151b3827dc08
--             savan         ac346752-d006-4ce2-811b-d17fe89a8f80
--             bhaveshbhai   bace87a1-86c3-4586-a056-24cdb2623348
--             shaileshbhai  a9e62532-80e3-4e95-a836-ebe0d3610ad0
--   Clients   Shree Demo Jewellers  233b206a-1d94-4c00-8956-4595909334e9
--             Royal Test Jewellers  9fdfc2d9-9264-412c-9e98-f40a857b318b
--
--   Passwords are NOT stored in this file; they were handed over privately.
--
-- Every block is safe to run again: it skips rows that already exist, and the
-- templates do nothing until you replace their <PLACEHOLDERS>.
-- =============================================================================


-- #############################################################################
-- 1. OWNER / PARTNER ACCOUNTS
-- #############################################################################

-- -----------------------------------------------------------------------------
-- 1a. Create the LOGIN (Auth user + identity).
--
--   EDIT for another owner:  username, password.
--
--   username  3–32 characters: lowercase a–z, digits, '.' or '_', starting with
--             a letter or digit. Must be unique across ALL businesses.
--   email     always <username>@login.vepari.invalid. Not a real mailbox;
--             nothing is ever emailed. Do not change the domain: the app adds it.
--   password  8–72 characters, not the same as the username. Tell it to the
--             person yourself; Vepari never sends it anywhere.
--   Auth UID  generated by Supabase (gen_random_uuid()). NEVER type one in.
--
--   The 5 partners were created with exactly this statement (passwords removed).
-- -----------------------------------------------------------------------------
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
    email_change_token_new, email_change, email_change_token_current, phone_change, phone_change_token,
    reauthentication_token, is_sso_user, is_anonymous)
select '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
       v.username || '@login.vepari.invalid',
       extensions.crypt(v.password, extensions.gen_salt('bf')),   -- stored as a bcrypt hash, never plain text
       now(),                                                     -- auto-confirmed
       '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '', false, false
  from (values
    ('newpartner', '<PASSWORD>')          -- ← EDIT: username, password
  ) as v(username, password)
 where v.password !~ '^<.*>$'                                     -- template guard: placeholder not replaced
   and length(v.password) between 8 and 72
   and lower(v.password) <> v.username
   and v.username ~ '^[a-z0-9][a-z0-9._]{2,31}$'
   and not exists (select 1 from auth.users u where u.email = v.username || '@login.vepari.invalid');

insert into auth.identities (id, provider_id, user_id, identity_data, provider, created_at, updated_at)
select gen_random_uuid(), u.id::text, u.id,
       jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true), 'email', now(), now()
  from auth.users u
 where u.email = 'newpartner@login.vepari.invalid'                -- ← EDIT: same username
   and not exists (select 1 from auth.identities i where i.user_id = u.id and i.provider = 'email');

-- Dashboard alternative to 1a: Authentication → Users → Add user → Create new
-- user (email as above, password, tick "Auto Confirm User"). Then copy the
-- user's UID. The blocks below look the UID up by email, so either route works.
-- If you prefer to paste it, replace the  (select id from auth.users where …)
-- part with  '<PASTE AUTH UID FROM SUPABASE AUTH>'::uuid .

-- -----------------------------------------------------------------------------
-- 1b. FIRST owner of a NEW business: creates the business and makes this login
--     its owner. Run only once per business. This is how Krish was set up.
-- -----------------------------------------------------------------------------
select public.admin_create_tenant(
         'vepari-manufacturer',             -- slug: internal business id; 3–40 chars, lowercase, digits, dashes; unique
         'Vepari Manufacturer (Demo)',      -- business name on bills (owners can rename it in the app)
         (select id from auth.users where email = 'krish@login.vepari.invalid'),   -- the Auth UID (from 1a)
         'krish',                           -- username (same as in the email)
         'Krish')                           -- display name shown in the app
 where not exists (select 1 from public.tenants where slug = 'vepari-manufacturer');

-- -----------------------------------------------------------------------------
-- 1c. MORE partners as owners of the SAME business. This is how Sujal, Savan,
--     Bhaveshbhai and Shaileshbhai were added.
--
--   EDIT for another owner: the (username, display name) row. Create the login
--   with 1a first. Keep 'vepari-manufacturer' so they join OUR business.
-- -----------------------------------------------------------------------------
select public.admin_add_member(
         (select id from public.tenants where slug = 'vepari-manufacturer'),   -- which business (by slug)
         u.id,                              -- the Auth UID, looked up by email
         v.username,
         v.display_name,
         'owner',                           -- role: 'owner' = partner with full access
         '{}')                              -- permissions: leave empty for owners (they have all)
  from (values
    ('sujal', 'Sujal'),
    ('savan', 'Savan'),
    ('bhaveshbhai', 'Bhaveshbhai'),
    ('shaileshbhai', 'Shaileshbhai')
    -- , ('newpartner', 'New Partner')     -- ← EDIT: add a row for another owner
  ) as v(username, display_name)
  join auth.users u on u.email = v.username || '@login.vepari.invalid'
 where not exists (select 1 from public.app_users a where a.id = u.id);

-- -----------------------------------------------------------------------------
-- 1d. EDIT an owner later (uncomment one line, edit, run).
--   Usernames cannot be renamed (the login email is built from them): create a
--   new login instead.
-- -----------------------------------------------------------------------------
-- Display name:
-- update public.app_users set display_name = 'Krishbhai' where username = 'krish';
-- New password (tell them in person):
-- update auth.users set encrypted_password = extensions.crypt('<NEW PASSWORD>', extensions.gen_salt('bf')), updated_at = now()
--  where email = 'krish@login.vepari.invalid';
-- Stop a partner's access (keep at least one active owner!):
-- update public.tenant_members set is_active = false
--  where user_id = (select id from auth.users where email = 'savan@login.vepari.invalid');

-- -----------------------------------------------------------------------------
-- 1e. CHECK: every owner of our business.
-- -----------------------------------------------------------------------------
select a.username, a.display_name, m.role, m.is_active, a.id as auth_uid, b.business_name
  from public.tenant_members m
  join public.app_users a on a.id = m.user_id
  join public.tenants t on t.id = m.tenant_id
  join public.business_profiles b on b.tenant_id = t.id
 where t.slug = 'vepari-manufacturer'
 order by m.role, a.username;


-- #############################################################################
-- 2. CLIENT / CUSTOMER ACCOUNTS
-- #############################################################################
--
-- A client (a jeweller who orders from us) is a row in public.customers that
-- belongs to OUR business. A client has no login, and is never a member.
--
--   client ID  customers.id: generated automatically (uuid). Use it to edit.
--   business   tenant_id: OUR business, looked up by slug. Never another business.
--   name       REQUIRED, 1–120 characters: the client as shown in the app
--   shop_name  optional, up to 120 characters
--   city       optional, up to 60 characters
--   phone, whatsapp_phone  optional, digits only, 10–15 (an optional leading +).
--              Use real numbers only: WhatsApp sharing sends to this number.
--   notes      optional, up to 1000 characters (staff can read them)
--
-- The client's Baki (balance) row is created automatically at 0. Set an opening
-- Baki in the app (Hisaab), never by writing balances or ledger rows here.
-- The two demo clients were created from Krish's login through the app's API
-- (created_by = Krish). Rows added here have no created_by.

-- -----------------------------------------------------------------------------
-- 2a. CREATE clients. EDIT: the rows (name, city, notes).
-- -----------------------------------------------------------------------------
insert into public.customers (tenant_id, name, city, notes)
select t.id, v.name, v.city, v.notes
  from public.tenants t
  cross join (values
    ('Shree Demo Jewellers', 'Demo City', 'DEMO client: fictional test data, not a real business.'),
    ('Royal Test Jewellers', 'Demo City', 'DEMO client: fictional test data, not a real business.')
    -- , ('New Client Jewellers', 'Rajkot', null)   -- ← EDIT: add a row for another client
  ) as v(name, city, notes)
 where t.slug = 'vepari-manufacturer'
   and not exists (select 1 from public.customers c where c.tenant_id = t.id and lower(c.name) = lower(v.name));

-- -----------------------------------------------------------------------------
-- 2b. EDIT a client later (uncomment, edit, run). Clients are archived, never
--     removed, because their orders and Hisaab must stay correct.
-- -----------------------------------------------------------------------------
-- update public.customers set city = 'Rajkot', shop_name = 'Shree Demo Jewellers'
--  where id = '233b206a-1d94-4c00-8956-4595909334e9';
-- Archive (hidden from lists, history kept):
-- update public.customers set archived_at = now() where id = '9fdfc2d9-9264-412c-9e98-f40a857b318b';

-- -----------------------------------------------------------------------------
-- 2c. CHECK: our clients, and that none of them is a login.
-- -----------------------------------------------------------------------------
select c.id as client_id, c.name, c.city, c.archived_at, b.balance_paise
  from public.customers c
  join public.tenants t on t.id = c.tenant_id
  left join public.customer_balances b on b.tenant_id = c.tenant_id and b.customer_id = c.id
 where t.slug = 'vepari-manufacturer'
 order by c.name;

select count(*) as clients_with_a_login     -- must be 0
  from public.app_users a
 where a.display_name in (select name from public.customers);


-- #############################################################################
-- 3. CHECK: owners and clients per business (each business sees only its own)
-- #############################################################################
select t.slug,
       b.business_name,
       (select count(*) from public.tenant_members m where m.tenant_id = t.id and m.role = 'owner') as owners,
       (select count(*) from public.tenant_members m where m.tenant_id = t.id and m.role = 'staff') as staff,
       (select count(*) from public.customers c where c.tenant_id = t.id) as clients
  from public.tenants t
  join public.business_profiles b on b.tenant_id = t.id
 order by t.slug;
